import { createClient } from '@supabase/supabase-js';

/**
 * BTCChain Supabase Configuration
 * 
 * IF YOU SEE "RELATION ALREADY EXISTS" OR "COLUMN NOT FOUND":
 * Run this 'Clean Slate' script in the Supabase SQL Editor:
 * 
 * DROP TABLE IF EXISTS waitlist;
 * 
 * CREATE TABLE waitlist (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   email TEXT UNIQUE NOT NULL,
 *   created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
 * );
 * 
 * ALTER TABLE waitlist ENABLE ROW LEVEL SECURITY;
 * CREATE POLICY "Allow public insert" ON waitlist FOR INSERT WITH CHECK (true);
 */

// @ts-ignore - Handle environment variable injection
const env = typeof process !== 'undefined' ? process.env : (import.meta as any).env || {};

// We use .trim() to ensure no accidental spaces break the connection
const rawUrl = env.VITE_SUPABASE_URL || 'YOUR_SUPABASE_URL';
const rawKey = env.VITE_SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY';

const supabaseUrl = rawUrl.trim();
const supabaseAnonKey = rawKey.trim();

// VALIDATION LOGIC
const isPlaceholder = supabaseUrl.includes('YOUR_SUPABASE_URL');
const isMissingProtocol = supabaseUrl !== '' && !supabaseUrl.startsWith('https://');
const isValidConfig = !isPlaceholder && !isMissingProtocol && supabaseUrl.length > 15;

if (!isValidConfig && typeof window !== 'undefined') {
  if (isMissingProtocol && !isPlaceholder) {
    console.error('❌ BTCChain Setup Error: Your VITE_SUPABASE_URL is invalid. It must start with "https://".');
  } else if (isPlaceholder) {
    console.info('ℹ️ BTCChain Status: Waiting for Supabase Environment Variables to be set in Vercel.');
  }
}

export const supabase = isValidConfig
  ? createClient(supabaseUrl, supabaseAnonKey)
  : {
      from: () => ({
        insert: async () => ({ 
          error: { 
            message: isMissingProtocol 
              ? 'Invalid Supabase URL (must start with https://)' 
              : 'Developer: Set Supabase URL & Key in environment variables.',
            code: 'MISSING_CONFIG'
          } 
        })
      })
    } as any;
